mixin () {
  /// Returns a static Markdown description of the backend's public API.
  public query func getApiDoc() : async Text {
    "# اخدمني — Backend API\n\n"
    # "Backend canister for the **اخدمني** academic-services request site. Visitors submit academic-service requests (homework, presentations, research, translation, programming, other) with their name and a contact phone number. The site owner (admin) reviews and manages those requests.\n\n"
    # "## Public methods\n\n"
    # "### `submitRequest(input : SubmitRequestInput) : async ServiceRequest`\n"
    # "Public, **no authentication required** (anonymous callers allowed). Creates a new request, assigns it a sequential `id` and a human-readable `reference` (`AKH-000001`), stores it with status `#new`, and sends notification emails.\n\n"
    # "`SubmitRequestInput`:\n"
    # "- `serviceType : ServiceType` — one of `#homework`, `#presentation`, `#research`, `#translation`, `#programming`, `#other`.\n"
    # "- `description : Text` — required, non-blank.\n"
    # "- `fullName : Text` — required, non-blank.\n"
    # "- `phone : Text` — required; digits plus `+ - ( )` and spaces only, 7–15 digits.\n"
    # "- `email : ?Text` — optional customer email; when present and non-empty the customer also receives a confirmation email.\n"
    # "- `university : ?Text` — optional.\n"
    # "- `deadline : ?Text` — optional free-text deadline.\n\n"
    # "Returns the created `ServiceRequest`.\n\n"
    # "### `listRequests(filter : RequestFilter) : async [ServiceRequest]`\n"
    # "**Admin only.** Returns requests matching the filter, newest first (`createdAt` descending). `RequestFilter` fields are all optional: `status : ?RequestStatus`, `serviceType : ?ServiceType`, `search : ?Text` (case-insensitive substring match over name, phone, reference, description).\n\n"
    # "### `getRequest(id : Nat) : async ?ServiceRequest`\n"
    # "**Admin only.** Returns the request with that `id`, or `null`.\n\n"
    # "### `updateRequestStatus(id : Nat, status : RequestStatus) : async ?ServiceRequest`\n"
    # "**Admin only.** Sets the request status to one of `#new`, `#inProgress`, `#completed`, `#cancelled`. Returns the updated request, or `null` when no request with that `id` exists.\n\n"
    # "### `getNotificationEmail() : async Text`\n"
    # "**Admin only.** Returns the configured notification recipient address. Defaults to `deeaalawwad00@gmail.com` and can be changed from the admin notification-settings page.\n\n"
    # "### `setNotificationEmail(email : Text) : async ()`\n"
    # "**Admin only.** Sets the notification recipient address. Setting it to the empty string disables the admin notification email.\n\n"
    # "### `getApiDoc() : async Text`\n"
    # "Public query. Returns this document.\n\n"
    # "## Authentication and authorization\n\n"
    # "- `submitRequest` and `getApiDoc` are open to everyone, including anonymous callers.\n"
    # "- Every other method is **admin only**. The caller's role is resolved from the authorization state; a non-admin caller traps with `Unauthorized: Only admins can perform this action`.\n"
    # "- The first caller to initialize access control becomes the admin; subsequent callers receive the default (non-admin) role. A caller that never registered through the app's frontend is unregistered even if it belongs to the owner, and a principal derived against a different origin is a different principal than the one the frontend registered.\n"
    # "- The frontend pins an Internet Identity derivation origin, published at `/.well-known/ii-derivation-origin` when available. An agent already holding the user's Internet Identity authorization derives the correct per-app principal against that origin (for example `icp identity link web <name> --app <host>`). Such a delegation acts with the user's full authority in this app until it expires.\n\n"
    # "## Units and encodings\n\n"
    # "- `createdAt` is a `Nat` timestamp in **nanoseconds since the Unix epoch** (`Time.now()`).\n"
    # "- `id` is a sequential `Nat` starting at 0.\n"
    # "- `reference` is `Text` formatted as `AKH-` followed by the zero-padded id (6 digits minimum).\n"
    # "- `email`, `university`, and `deadline` are optional (`?Text`); `null` means not provided.\n"
    # "- `serviceType` and `status` are Candid variants, encoded by tag name.\n\n"
    # "## Lifecycle and polling\n\n"
    # "- A request is created with status `#new` and moves through `#inProgress`, `#completed`, or `#cancelled` only via `updateRequestStatus` (admin).\n"
    # "- There is no push channel. Clients poll `listRequests` / `getRequest` to observe status changes.\n"
    # "- `listRequests` returns a full snapshot; there is no pagination.\n\n"
    # "## Mutation retry safety\n\n"
    # "- `submitRequest` is **not idempotent**: each successful call creates a new request with a new id and sends new emails. Retrying after a timeout may create a duplicate.\n"
    # "- `updateRequestStatus` is idempotent for a given `(id, status)` pair.\n"
    # "- `setNotificationEmail` is idempotent.\n\n"
    # "## Errors, traps, and gotchas\n\n"
    # "- `submitRequest` traps with an Arabic validation message when `fullName` or `description` is blank, or when `phone` is missing/malformed.\n"
    # "- **A notification-email failure never traps `submitRequest`.** The request is stored first; the admin notification and the customer confirmation are then sent best-effort. If the email service returns an error, the failure is swallowed and the request remains stored — the customer sees no error. When the notification email is empty, no admin email is sent and the request is stored normally.\n"
    # "- Admin-guarded methods trap for non-admin callers rather than returning an error variant.\n"
    # "- `updateRequestStatus` and `getRequest` return `null` for an unknown id; they do not trap.\n";
  };
};
