/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const RequestStatus = IDL.Variant({
  'new' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'other' : IDL.Null,
  'research' : IDL.Null,
  'homework' : IDL.Null,
  'translation' : IDL.Null,
  'presentation' : IDL.Null,
  'programming' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const RequestReference = IDL.Text;
export const ServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'serviceType' : ServiceType,
  'createdAt' : Timestamp,
  'reference' : RequestReference,
  'fullName' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'university' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const RequestFilter = IDL.Record({
  'status' : IDL.Opt(RequestStatus),
  'serviceType' : IDL.Opt(ServiceType),
  'search' : IDL.Opt(IDL.Text),
});
export const SubmitRequestInput = IDL.Record({
  'serviceType' : ServiceType,
  'fullName' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'university' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNotificationEmail' : IDL.Func([], [IDL.Text], ['query']),
  'getRequest' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceRequest)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listRequests' : IDL.Func(
      [RequestFilter],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setNotificationEmail' : IDL.Func([IDL.Text], [], []),
  'submitRequest' : IDL.Func([SubmitRequestInput], [ServiceRequest], []),
  'updateRequestStatus' : IDL.Func(
      [IDL.Nat, RequestStatus],
      [IDL.Opt(ServiceRequest)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const RequestStatus = IDL.Variant({
    'new' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'other' : IDL.Null,
    'research' : IDL.Null,
    'homework' : IDL.Null,
    'translation' : IDL.Null,
    'presentation' : IDL.Null,
    'programming' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const RequestReference = IDL.Text;
  const ServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
    'serviceType' : ServiceType,
    'createdAt' : Timestamp,
    'reference' : RequestReference,
    'fullName' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'university' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const RequestFilter = IDL.Record({
    'status' : IDL.Opt(RequestStatus),
    'serviceType' : IDL.Opt(ServiceType),
    'search' : IDL.Opt(IDL.Text),
  });
  const SubmitRequestInput = IDL.Record({
    'serviceType' : ServiceType,
    'fullName' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'university' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNotificationEmail' : IDL.Func([], [IDL.Text], ['query']),
    'getRequest' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceRequest)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listRequests' : IDL.Func(
        [RequestFilter],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setNotificationEmail' : IDL.Func([IDL.Text], [], []),
    'submitRequest' : IDL.Func([SubmitRequestInput], [ServiceRequest], []),
    'updateRequestStatus' : IDL.Func(
        [IDL.Nat, RequestStatus],
        [IDL.Opt(ServiceRequest)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };