/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface RequestFilter {
  'status' : [] | [RequestStatus],
  'serviceType' : [] | [ServiceType],
  'search' : [] | [string],
}
export type RequestReference = string;
export type RequestStatus = { 'new' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface ServiceRequest {
  'id' : bigint,
  'status' : RequestStatus,
  'serviceType' : ServiceType,
  'createdAt' : Timestamp,
  'reference' : RequestReference,
  'fullName' : string,
  'description' : string,
  'deadline' : [] | [string],
  'email' : [] | [string],
  'university' : [] | [string],
  'phone' : string,
}
export type ServiceType = { 'other' : null } |
  { 'research' : null } |
  { 'homework' : null } |
  { 'translation' : null } |
  { 'presentation' : null } |
  { 'programming' : null };
export interface SubmitRequestInput {
  'serviceType' : ServiceType,
  'fullName' : string,
  'description' : string,
  'deadline' : [] | [string],
  'email' : [] | [string],
  'university' : [] | [string],
  'phone' : string,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Returns a static Markdown description of the backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Admin-only: read the configured notification recipient address.
   */
  'getNotificationEmail' : ActorMethod<[], string>,
  /**
   * / Admin-only: fetch a single request by id.
   */
  'getRequest' : ActorMethod<[bigint], [] | [ServiceRequest]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Admin-only: list requests with optional status / service-type / search filters.
   */
  'listRequests' : ActorMethod<[RequestFilter], Array<ServiceRequest>>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Admin-only: set the notification recipient address.
   */
  'setNotificationEmail' : ActorMethod<[string], undefined>,
  /**
   * / Public endpoint: submit a new academic-service request. No authentication
   * / required. Returns the created request including its reference number.
   */
  'submitRequest' : ActorMethod<[SubmitRequestInput], ServiceRequest>,
  /**
   * / Admin-only: change the status of a request.
   */
  'updateRequestStatus' : ActorMethod<
    [bigint, RequestStatus],
    [] | [ServiceRequest]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];